### ISSUE TITLE
Can't resume from file both on win/linux

### ISSUE THREAD

**Issue by k79e** [nmap/ncrack#102]
On linux it said segment error
On win it says 
```
Corrupted file! Error 7

QUITTING!
```

**Comment by ithilgore** [comment]
What was the command you invoked Ncrack with?

**Comment by k79e** [comment]
It's like this
ncrack --save nck --user root -P xxx.txt -g cl=20,CL=300,at=4,cd=50ms -p ssh -iL iplist/input.txt --connection-limit 400 --append-output -oN output

**Comment by k79e** [comment]
Some addition info

#0  0x0000555555567120 in ?? ()
No symbol table info available.
#1  0x0000555555562e4e in ?? ()
No symbol table info available.
#2  0x000055555555e04c in ?? ()
No symbol table info available.
#3  0x00007ffff778c09b in __libc_start_main (main=0x55555555dfe0, argc=3,
    argv=0x7fffffffec08, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7fffffffebf8)
    at ../csu/libc-start.c:308
        self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, -4296641986342774840,
                93824992273024, 140737488350208, 0, 0, -7995552171623802936,
                -7995570870531352632}, mask_was_saved = 0}}, priv = {pad = {
              0x0, 0x0, 0x7fffffffec28, 0x7ffff7ffe190}, data = {prev = 0x0,
              cleanup = 0x0, canceltype = -5080}}}
        not_first_call = <optimized out>
#4  0x000055555555e2aa in ?? ()
No symbol table info available.
