### ISSUE TITLE
FTBFS: configure:6846: error: ./configure failed for opensshlib

### ISSUE THREAD

**Issue by MarcosFouces** [nmap/ncrack#15]
Dear upstream,
We noticed that ncrack fails to build from source with openssl 1.1.0
You can see full details here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=844303

Greetings

**Comment by ithilgore** [comment]
I'll look into it. Thanks for the report.

**Comment by ithilgore** [comment]
OpenSSL 1.1.0 isn't currently supported by even the latest OpenSSH (7.3) on which Ncrack's opensshlib is based. Until OpenSSH fixes that, this issue will be closed.

**Comment by xambroz** [comment]
Fedora will be probably moving to openssl 1.1.0 with next release of Fedora 26.
