### ISSUE TITLE
ncrack

### ISSUE THREAD

**Issue by wavyado** [nmap/ncrack#21]
Hello,

I am trying to brute force on a non-standard port 2222 sftp. I added the new port and the service name in ncrack-services as sssh 2222/tcp, when running the following command 

ncrack -vv -user acb -pass password <IP>:2222 i received the following error:

Starting Ncrack 0.5 ( http://ncrack.org ) at 2017-06-01 07:34 EDT

Invalid service module: sssh
QUITTING!

Kindly advise how i can successfully perform a successful brute fore with no errors.

As per my understanding there is also ssl certificate in the session, should we add also the ssl before starting the brutefore ?

Thanks in Advance 

Below is the telnet results of port 2222:

SSH-2.0-mod_sftp/0.9.9
╘{Ä!PÜ╔wo^⌡├gÄ5─ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,rsa1024-sha1ssh-rsa,ssh-dss aes128-ctr,aes192-ctr,aes256-ctr aes128-ctr,aes192-ctr,aes256-ctr%hmac-sha1,hmac-sha2-256,hmac-sha2-512%hmac-sha1,hmac-sha2-256,hmac-sha2-512zlib@openssh.com,zlib,nonezlib@openssh.com,zlib,noneΦoÇ

**Comment by BarrendG** [comment]
Hello wavyado,
If you want to bruteforce a non-standard port which uses one of the implemented protocols-services, you can change the port number at the ncrack-services file. You recompile and you are ready to go. SFTP probably uses the same authentication method as ssh so you can change ncrack-services ssh's port to 2222, recompile and give it a try.
