### ISSUE TITLE
XML output

### ISSUE THREAD

**Issue by pbespechnyi** [nmap/ncrack#30]
Hi guys,

I've tried to get XML results using following command:
`ncrack <host> -p ssh -v -T5 --user root --pass toor -oX -`

Output is:
```
Ncrack 0.5 scan initiated Tue Sep 12 00:53:09 2017 as:  />

EOF
```
Same message I get when pass file name instead `-`.

Is there an option to output XML to stdout?

BTW, where can I found XML schema definitions or at least example output?

**Comment by ithilgore** [comment]
XML support will be added in the 0.7 release

**Comment by ithilgore** [comment]
Experimental XML support added at: https://github.com/nmap/ncrack/commit/d3455ca1807d93a1b6e13193014d1b28f792fe3e
