### ISSUE TITLE
IPv6 Address Error

### ISSUE THREAD

**Issue by h2odriving** [nmap/ncrack#31]
HI guys,

I encountered a problem with ncrack and IPv6 addresses. If I try to use an IPv6 address instead of an Hostname ncrack quit with the error message that the port number is invalid. Since there are no good information on how to provide an IPv6 address to ncrack I tried various but all getting to the same error. It looks like that ncrack tries to interpret everything after the first colon as a port number.

```
#ncrack -6 -v --user=root --pass=test [2001:db8::2]:22

Starting Ncrack 0.5 ( http://ncrack.org ) at 2017-09-15 06:08 EDT

Invalid port number: db8::2]:22
QUITTING!

# ncrack -6 -v --user=root --pass=test "[2001:db8::2]:22"

Starting Ncrack 0.5 ( http://ncrack.org ) at 2017-09-15 06:08 EDT

Invalid port number: db8::2]:22
QUITTING!

# ncrack -6 -v --user=root --pass=test "[2001:db8::2]":22

Starting Ncrack 0.5 ( http://ncrack.org ) at 2017-09-15 06:08 EDT

Invalid port number: db8::2]:22
QUITTING!

# ncrack -6 -v --user=root --pass=test "2001:db8::2":22

Starting Ncrack 0.5 ( http://ncrack.org ) at 2017-09-15 06:09 EDT

Invalid port number: db8::2:22
QUITTING!

#ncrack -6 -v --user=root --pass=test ssh://[2001:db8::2]

Starting Ncrack 0.5 ( http://ncrack.org ) at 2017-09-15 06:10 EDT

Invalid port number: db8::2
QUITTING!

#ncrack -6 -v --user=root --pass=test ssh://2001:db8::2

Starting Ncrack 0.5 ( http://ncrack.org ) at 2017-09-15 06:10 EDT

Invalid port number: db8::2
QUITTING!
```

It would be great if some of you guys can check if this is an issue or tell in which form an IPv6 address should be provided to ncrack.
A quick solution for me was to create a hosts entry with the IPv6 address and use the hostname instead.

**Comment by ithilgore** [comment]
Thanks for bringing this to our attention. This is definitely a parsing issue indeed. Will look into it.
