### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by wermaxta** [nmap/ncrack#33]
Hi i have problem to install ncrack 0.6
My OS is Linux kali 4.13.0-kali1-amd64 #1 SMP Debian 4.13.4-2kali1 (2017-10-16) x86_64 GNU/Linux
ncrack# openssl version
OpenSSL 1.1.0f  25 May 2017
 i got this message 
configure: error: Your OpenSSL headers do not match your
	library. Check config.log for details.
	If you are sure your installation is consistent, you can disable the check
	by running "./configure --without-openssl-header-check".
	Also see contrib/findssl.sh for help identifying header/library mismatches.
	
configure: error: ./configure failed for opensshlib

Thank you :)

**Comment by ithilgore** [comment]
Use "apt install libssl1.0-dev" to compile on Kali Linux. It needs older SSL version due to OpenSSH code for SSH module.

**Comment by MarcosFouces** [comment]
Hello

Did you have any plans to port ncrack to openssl 1.1?

libssl1.0 will surely be removed from Debian very soon. In fact all
packages depending on it are candidates to removal by now.

Greetings,

Marcos

**Comment by ithilgore** [comment]
It all depends on whether the OpenSSH code is going to be upgraded to support openssl 1.1 (Ncrack uses the OpenSSH codebase for its SSH module). As of now, OpenSSH 7.6p1 requires: 
OpenSSL >= 0.9.8f < 1.1.0
(or LibreSSL)
