### ISSUE TITLE
Invalid service module: ms-wbt-server

### ISSUE THREAD

**Issue by 0c0c0f** [nmap/ncrack#37]
➜  tools ncrack -vv -u root -P 500-worst-passwords.txt 192.168.31.36:3389           

Starting Ncrack 0.7 ( http://ncrack.org ) at 2018-03-25 13:52 CST

Invalid service module: ms-wbt-server
QUITTING!

platform macos 10.13.3

how can i solve this problem？

**Comment by ithilgore** [comment]
You probably compiled Ncrack without SSL/TLS support and hence the RDP module wasn't compiled in. You should download the latest openssl version (1.1.x) and recompile Ncrack with it.

**Comment by 0c0c0f** [comment]
Is there hava a document?

**Comment by mizogomo** [comment]
https://www.linuxhelp.com/how-to-install-and-update-openssl-on-ubuntu-16-04/
