### ISSUE TITLE
can't build: collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by AddaxSoft** [nmap/ncrack#42]
```
/home/ubuntu/ncrack/opensshlib/ssh-rsa.c:135: undefined reference to `RSA_get0_key'
opensshlib/libopenssh.a(dh.o): In function `dh_pub_is_valid':
/home/ubuntu/ncrack/opensshlib/dh.c:240: undefined reference to `DH_get0_pqg'
opensshlib/libopenssh.a(dh.o): In function `dh_gen_key':
/home/ubuntu/ncrack/opensshlib/dh.c:267: undefined reference to `DH_get0_pqg'
/home/ubuntu/ncrack/opensshlib/dh.c:273: undefined reference to `DH_set_length'
/home/ubuntu/ncrack/opensshlib/dh.c:274: undefined reference to `DH_get0_key'
opensshlib/libopenssh.a(dh.o): In function `dh_new_group_asc':
/home/ubuntu/ncrack/opensshlib/dh.c:290: undefined reference to `DH_get0_pqg'
opensshlib/libopenssh.a(dh.o): In function `dh_new_group':
/home/ubuntu/ncrack/opensshlib/dh.c:311: undefined reference to `DH_set0_pqg'
collect2: error: ld returned 1 exit status
Makefile:65: recipe for target 'ncrack' failed
```

I'm on:
`Linux HOST 4.13.0-1013-gcp #17-Ubuntu SMP Fri Apr 6 08:30:45 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

```

I've already installed the following dependencies:
`apt-get install git build-essential libssl-dev -y`

and cloned the latest git from here.

**Comment by ithilgore** [comment]
Please try compiling with openssl 1.1 and above. You are probably linking with an older version of openssl

**Comment by AddaxSoft** [comment]
sanity check: you mean libssl-dev 1.1?

**Comment by ithilgore** [comment]
Yes, but since your ubuntu version might not have 1.1 as a package, you can also try getting it directly from https://www.openssl.org/

**Comment by AddaxSoft** [comment]
I compiled and installed openssl 1.1, but 

I'm getting this error on ./configure now:
```
checking OpenSSL header version... 1010006f (OpenSSL 1.1.0f  25 May 2017)
checking OpenSSL library version... not found
configure: error: OpenSSL library not found.
configure: error: ./configure failed for opensshlib
```



```
openssl version
OpenSSL 1.1.0f  25 May 2017
```

**Comment by ithilgore** [comment]
Did you also try uninstalling the libssl-dev package from previously to avoid any conflicts?

**Comment by ithilgore** [comment]
Also make sure that in /etc/ld.so.conf, there is a "/usr/local/lib" before the end of the file.
Then: sudo ldconfig

**Comment by AddaxSoft** [comment]
same error, hmmm do I have to rebuild and install openssl after I remove ssllib?

**Comment by ithilgore** [comment]
You can also try installing openssl using the --prefix /usr when you invoke ./config so that it's not at the /usr/local/  (might also need to change the --openssldir) See: https://github.com/openssl/openssl/blob/master/INSTALL

**Comment by ithilgore** [comment]
One more thing to try is when you run ./configure from Ncrack try specifying the openssl library location using --with-openssl=

**Comment by AddaxSoft** [comment]
wow I spent so much time on this and I still cannot get it right. I did compile openssl 1.1 and installed it but it doesn't recognize its own library.

On one box I have:
```
OpenSSL 1.1.0g  2 Nov 2017 **(Library: OpenSSL 1.1.0h  27 Mar 2018)**
built on: reproducible build, date unspecified
platform: debian-amd64
compiler: gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/lib/ssl\"" -DENGINESDIR="\"/usr/lib/x86_64-linux-gnu/engines-1.1\""
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-1.1"
```

on the other where nrack fails I have:
```
OpenSSL 1.1.0h  27 Mar 2018
built on: reproducible build, date unspecified
platform: linux-x86_64
options:  bn(64,64) rc4(16x,int) des(int) idea(int) blowfish(ptr)
compiler: gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\""  -Wa,--noexecstack
OPENSSLDIR: "/usr/local/ssl"
ENGINESDIR: "/usr/local/lib/engines-1.1"
```


What am I missing here? why is openssl not recognizing its own library making ncrack fail

**Comment by denevin** [comment]
@AddaxSoft.
I was able to compile it on Kali by running "apt-get install git build-essential libssl-dev -y", followed by "make clean" then make

**Comment by AddaxSoft** [comment]
@denevin 

but I'm not on kali, I'm on Ubuntu (see `uname -a` command outputs above)

**Comment by AddaxSoft** [comment]
after all the efforts I'm still getting the same issue.

my `ldconfig -v` reports ssllib1.1 being in the path of libs
```
/usr/local/lib:
        libssl.so.1.1 -> libssl.so.1.1
        libcrypto.so.1.1 -> libcrypto.so.1.1
```

openssl version -a reports the correct version, yet ncrack still fails to configure with error:
```
checking OpenSSL header version... 1010008f (OpenSSL 1.1.0h  27 Mar 2018)
checking OpenSSL library version... not found
configure: error: OpenSSL library not found.
configure: error: ./configure failed for opensshlib
```

**Comment by AddaxSoft** [comment]
**half solution**:

compile and install openssl 1.1 from source
```
wget http://www.openssl.org/source/openssl-1.1.0h.tar.gz
tar -xvzf openssl-1.0.0a.tar.gz
cd openssl-1.1.0h/
./config && make && make install
```

then go back to ncrack dir, and run `make clean` 
after it's done run the following:
```
./configure --with-ssl-dir=/usr/local
make && make install
```
now make fails at:

```
In file included from cipher.c:46:0:
cipher.h:69:17: error: field ‘evp’ has incomplete type
  EVP_CIPHER_CTX evp;
                 ^
Makefile:71: recipe for target 'cipher.o' failed
make[1]: *** [cipher.o] Error 1
```

**Comment by ithilgore** [comment]
There is no --with-ssl-dir switch in the configure of Ncrack. This will be ignored by the configure script. As I mentioned above the correct one is: --with-openssl. So try: ./configure --with-openssl=/usr/local

**Comment by AddaxSoft** [comment]
I updated my solution, but the script still fails now see #43

**Comment by AddaxSoft** [comment]
I'm back at square one now, the configure scriptt fails at 

```
checking OpenSSL header version... 1010008f (OpenSSL 1.1.0h  27 Mar 2018)
checking OpenSSL library version... not found
configure: error: OpenSSL library not found.
configure: error: ./configure failed for opensshlib
```

I tried everything so far
- ldconfig trick
- reinstalling openssl 1.10h (default)
- adding --wth-openssl=/usr/dir


?????????

**Comment by ithilgore** [comment]
do a cat /etc/issue for me 

I ll try to replicate it in the same ubuntu version and come back to you with the steps

**Comment by AddaxSoft** [comment]
`Ubuntu 16.04.4 LTS \n \l`

I tried to do the same on another same ubuntu image and it worked same steps as I described in my 'half solution' (https://github.com/nmap/ncrack/issues/42#issuecomment-395393678)


I'm not sure what did I mess up while doing this, because at some point I Got it working then it failed with #43 but now I'm back at square one.

**Comment by AddaxSoft** [comment]
update: 

I finally (after 48 hrs) managed to solve all issues.
this is the solution step by step:

```
# remove old ssllib 
 apt remove libssl-dev

# install openssl 1.10h from source
wget http://www.openssl.org/source/openssl-1.1.0h.tar.gz
tar -xvzf openssl-1.1.0h.tar.gz
cd openssl-1.1.0h/
./config && make && make install && ldconfig
openssl version -a #should report 1.1.0h now

# compile ncrack
/path/to/ncrack/configure && make && make install
```

Apparently during my process to fix the issue with ssllib I managed to mess the system structure; somehow removing ssllib-dev then installing openssl fixed the issue
