### ISSUE TITLE
cannot 'make' fails at: /usr/bin/ld: cannot find -lopenssh

### ISSUE THREAD

**Issue by AddaxSoft** [nmap/ncrack#43]
It has been 24 hours trying to compile this source. I've opened an issue here #42 and talked with openssl guys. This seems to be a bug at configure.as not checking a none default openssl path.

Now that's fixed however I'm failing at:
```
g++ -L/usr/local/lib -Lnbase -Lnsock/src -L/usr/local   -o ncrack ncrack.o utils.o TargetGroup.o Target.o targets.o NcrackOps.o Service.o ServiceGroup.o Connection.o services.o timing.o ncrack_error.o output.o ncrack_tty.o Buf.o NcrackOutputTable.o ncrack_input.o ncrack_resume.o crypto.o http.o http_digest.o xml.o modules/ncrack_ssh.o modules/ncrack_smb.o modules/ncrack_rdp.o modules/ncrack_sip.o modules/ncrack_psql.o modules/ncrack_mysql.o modules/ncrack_winrm.o modules/ncrack_mongodb.o modules/ncrack_ftp.o modules/ncrack_telnet.o modules/ncrack_http.o modules/ncrack_pop3.o modules/ncrack_vnc.o modules/ncrack_redis.o modules/ncrack_owa.o modules/ncrack_imap.o modules/ncrack_cassandra.o modules/ncrack_mssql.o modules/ncrack_cvs.o modules/ncrack_wordpress.o modules/ncrack_joomla.o -lnsock -lnbase -lssl -lcrypto -lopenssh
/usr/bin/ld: cannot find -lopenssh
```

I did some googling, and one of the suggested soluions was to copy libssh.so library to /usr/lib/, this is not working however - what to do next?

**Comment by ithilgore** [comment]
The final g++ command normally is including -Lopensshlib (g++ -Lnbase -Lnsock/src -Lopensshlib   -o ncrack ...) Make sure that the Ncrack Makefile still has the LDFLAGS like this:

LDFLAGS =  -Lnbase -Lnsock/src -Lopensshlib $(DBGFLAGS) $(STATIC)

and that if you are overriding the LDFLAGS variable in your environment (using export LDFLAGS before calling make) it still includes the -Lopensshlib directive

**Comment by AddaxSoft** [comment]
I have 

```
LDFLAGS =  -L/usr/local/lib -Lnbase -Lnsock/src -L/usr/local $(DBGFLAGS) $(STATIC)
        $(CXX) $(LDFLAGS) -o $@ $(OBJS) $(MOD_OBJS) $(LIBS)

```

**Comment by ithilgore** [comment]
Add  -Lopensshlib in there. By default the Makefile should have that in there

**Comment by AddaxSoft** [comment]
ok I managed to solve this issue from root - see https://github.com/nmap/ncrack/issues/42#issuecomment-395656613

please close this
