### ISSUE TITLE
muti threading when targeting a list

### ISSUE THREAD

**Issue by AddaxSoft** [nmap/ncrack#44]
while testing ncrack, I cannot see that it muti thread brute forcing for multiple targets in parallel 
This is a suggestion to implement multi threading.

**Comment by ithilgore** [comment]
Ncrack uses asynchronous network sockets based on the Nsock library to achieve parallelism. It doesn't need threads. See: https://sock-raw.org/nmap-ncrack/nsock.html 
and http://www.nightmare.com/medusa/async_sockets.html for examples on asynchronous socket programming
