### ISSUE TITLE
ncrack problem

### ISSUE THREAD

**Issue by MrCrypt99** [nmap/ncrack#46]
HI dear,
when I start a brute force operation with this command: ncrack -U user.txt -P pass.txt 127.0.0.1:22 I receive the error message: failed to open input file users.txt for reading!
Quitting! if instead I write on the terminal in this way:
ncrack -U user -P pass 127.0.0.1:22
I get the problem: segmentation error how can I solve the problem?

**Comment by ithilgore** [comment]
Are you sure these files (user.txt and pass.txt) are on the local directory from where you are running ncrack (otherwise specify the full path)? Also the error message seems to be about users.txt (with an 's') so maybe you mistyped that?
