### ISSUE TITLE
Ncrack not show data?

### ISSUE THREAD

**Issue by JannisFreimann** [nmap/ncrack#48]
Starting Ncrack 0.6 ( http://ncrack.org ) at 2018-08-03 19:45 CEST

Ncrack done: 1 service scanned in 3.00 seconds.

Ncrack finished.

https://gyazo.com/ca77a020dcb46d107985bc1b64024e9a

**Comment by ithilgore** [comment]
Are there services listening on those ports? Can you paste the output of the same commands with the addition of the -d10 command-line option?

**Comment by JannisFreimann** [comment]
Listening on Port 80.

https://gyazo.com/6276ab045325fed2917f046be51fec24

**Comment by ithilgore** [comment]
It seems that you need to point it to the right directory where there is an authentication page. Try using path=/auth-path after the service.  Example:
ncrack http://192.168.1.10,path=/auth.html

**Comment by JannisFreimann** [comment]
https://gyazo.com/446582069811c9cdab61ad41325dd0bc

**Comment by ithilgore** [comment]
auth.html was just an example - you have to use a real path of a directory that actually contains an authentication page/portal.
