### ISSUE TITLE
Duplicate service error after the newest git update

### ISSUE THREAD

**Issue by noleaknaynay** [nmap/ncrack#58]
I'm getting this error atm
 ncrack -v  -U ~/usr.txt -P ~/pw.txt -T5 -iN ~/result.txt

''
No options specified for module: RDP . Ignoring...

Starting Ncrack 0.7 ( http://ncrack.org ) at 2019-06-07 16:41

Duplicate service ms-wbt-server for target 37.xxx.xxx.xxx !
QUITTING!
'''

**Comment by ithilgore** [comment]
Can you post a portion of results.txt (you can omit any sensitive information)?

**Comment by noleaknaynay** [comment]
# Nmap 7.70 scan initiated as: nmap -p 3389 -n -iL ranges.txt -oN result.txt
Nmap scan report for xxx.xxx.xxx.208
Host is up (0.0061s latency).

PORT     STATE  SERVICE
3389/tcp closed ms-wbt-server

Nmap scan report for xxx.xxx.xxx.209
Host is up (0.0061s latency).

PORT     STATE  SERVICE
3389/tcp closed ms-wbt-server

Nmap scan report for xxx.xxx.xxx.210
Host is up (0.0061s latency).

PORT     STATE  SERVICE
3389/tcp closed ms-wbt-server

**Comment by ithilgore** [comment]
This is the same as the one you posted in the other issue and it does not trigger what you mentioned. It must be another part of the file that does this. Is the file too big to paste it whole (without the real IP addresses)?

**Comment by noleaknaynay** [comment]
When I try running just the block on that i've posted I get an error no services specified instead.
I've checked the filed there are no inconsistencies,  begins with 
`# Nmap 7.70 scan initiated as: nmap -p 3389 -n -iL ranges.txt -oN result.txt`
Ends with # Nmap finished scan, and a lot of blocks like the one i've posted in between.
The file is too big to post mask all all the IP's though.

**Comment by ithilgore** [comment]
It's normal to return the "no services specified" message because all the ports shown in that portion of the file are closed and hence Ncrack will not try to crack them.  

The "duplicate service" error on the other hand is triggered when the same host/IP with the same combination of protocol and port has been specified more than once as a target.

**Comment by tutanota** [comment]
> I'm getting this error atm
> ncrack -v -U ~/usr.txt -P ~/pw.txt -T5 -iN ~/result.txt
> 
> ''
> No options specified for module: RDP . Ignoring...
> 
> Starting Ncrack 0.7 ( http://ncrack.org ) at 2019-06-07 16:41
> 
> Duplicate service ms-wbt-server for target 37.xxx.xxx.xxx !
> QUITTING!
> '''

i need talk to you, please email me trabajos@ tutanota.com
