### ISSUE TITLE
Ncrack problem

### ISSUE THREAD

**Issue by mellisarunn** [nmap/ncrack#59]
Hi there,
When i start a bruteforce operation with the following command 
ncrack -p 3389 -iL host.txt -U user.txt -P pass.txt CL=2 at=2 cd=1m -oN Results -v -sL -f -d --passwords-first
i get a "failed to open input file host.txt for reading"

But when i run this command 
ncrack -p 3389 107.128.97.18 -U user.txt -P pass.txt CL=2 at=2 cd=1m -oN Results -v -sL -f -d --passwords-first it works.

However i have a bunch of ips i want to check and can't afford to input them in one by one.

Thanks for your time and good work!

PS running ncrack on windows 7

**Comment by ithilgore** [comment]
This seems like an error related with where the file is (and if your user has permissions to read it). Is it in your local directory or in your $PATH?

**Comment by mellisarunn** [comment]
Thanks for your response. 
And its in the same directory as the pass and user file. And they work just fine.
![for git](https://user-images.githubusercontent.com/51389905/59240559-a3dbe100-8bd2-11e9-8176-eedc0b54a649.PNG)

**Comment by ithilgore** [comment]
How is the ip.txt structured? Is an IP address per line?

**Comment by mellisarunn** [comment]
Yes, it is an IP address per line structure.
To troubleshoot, i have created several txt files with different ips and amount. It still gives the same error. -iL just doesn't seem to be working on my end.

On a different issue, the attached image is a scan i did on just one ip. Its been like that for over 12 hours. I've tried it with different other ips. Sometimes i get an "unable to resolve host" error and scan ends immediately. Or with some i get this.. 
![Capture 2](https://user-images.githubusercontent.com/51389905/59283659-e506dc00-8c38-11e9-9db9-00cd3ce0ef5b.PNG)

**Comment by ithilgore** [comment]
1. -u (that you are using) should be -U if you want to read usernames from a file. -u will be interpreted as a single username argument.

2. I tried to replicate the error on Windows with all the same arguments and I can't reproduce it. Does your Windows workstation have any weird group policies configured? Are you running the command as a user with Administrator privileges (although you shouldn't need to) ?

3. Try using the -d10 command-line argument to see some additional debug output

**Comment by mellisarunn** [comment]
I think it might be due to some group policies. I just only now noticed that even though i have admin access, for some reason i don't have total admin rights. Trying to fix that now.

Also using the -U command instead of -u fixed my hanging problem. I was able to successfully run a scan on an IP.

**Comment by ithilgore** [comment]
Perfect!

**Comment by De2d** [comment]
![image](https://user-images.githubusercontent.com/113767837/190850885-5f7a84c9-43ae-4ae7-8b98-6605d7e026ff.png)
what is the problem

**Comment by De-Been-Tech-Solutions** [comment]
Using this: ncrack -p 80 *insert.ip.address.here* -U user.txt -P pass.txt CL=2 at=2 cd=1m -oN Results -v -sL -f -d --passwords-first also fails for me.

**Comment by supersourix** [comment]
Same, full privileges.
