### ISSUE TITLE
how can i use it with a custom port ? 

### ISSUE THREAD

**Issue by minanagehsalalma** [nmap/ncrack#61]
this the command but it does nothing ..  it just keeps counting the time . does it work or there is another parameters ? 

`ncrack -v http://ip:8080  --user admin -P passlist.txt`

**Comment by ithilgore** [comment]
Yes, that is how you are supposed to use it with a custom port. You can also see some debugging output of what's happening behind the scenes by adding the -d10 command-line argument. The http module supports basic and digest authentication. For form authentication there is limited support for specific web apps like wordpress - there is a separate wordpress module (and joomla is WIP).

**Comment by minanagehsalalma** [comment]
Ok thanks

**Comment by minanagehsalalma** [comment]
Ok thanks
