### ISSUE TITLE
Ncrack fails to load large list of hosts

### ISSUE THREAD

**Issue by arjunv** [nmap/ncrack#67]
When more than 10K hosts are provided, ncrack hangs without any response.

**Comment by ithilgore** [comment]
Can you give some more details on how you reproduced this? I was able to use Ncrack to parse 10K hosts:

nmap -iR 10000 -sL -n | cut -d " " -f5 > ~/ip.txt
/ncrack -iL ../ip.txt -sL -d10 -p80

(I used -sL so that it doesn't actually try to do anything with the random hosts)
