### ISSUE TITLE
LGTM.com findings for Ncrack

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/ncrack#72]
Ncrack currently has a "D" code quality score from LGTM.com. This free static analysis site should be consulted in order to improve code quality and security. Updating the `nbase` and `nsock` directories from Nmap will help address some of these. Suggested sub-tasks:

- [ ] All [Security-tagged issues](https://lgtm.com/projects/g/nmap/ncrack?mode=list&result_filter=0e00f5fa7b93849767c1677dc71d9400f85c6a54) addressed
- [ ] All [Error-severity issues](https://lgtm.com/projects/g/nmap/ncrack?mode=list&severity=error) addressed
- [ ] All [Warning-severity issues](https://lgtm.com/projects/g/nmap/ncrack?mode=list&severity=warning) addressed
- [ ] LGTM configuration file added.

For that last point, a simple `.lgtm.yml` file containing the following information would ignore all issues in the `opensshlib` directory, since those are 3rd-party code:

```yml
path_classifiers:
  library:
    - opensshlib
```

**Comment by ithilgore** [comment]
Agreed. Let's address these. 

Opensshlib does have some minimal manual code though because of the bindings with Nsock and Ncrack handlers (see https://seclists.org/nmap-dev/2009/q3/428)

**Comment by ithilgore** [comment]
Code quality is now A :) 

https://lgtm.com/projects/g/nmap/ncrack/?mode=list
