### ISSUE TITLE
ncrack fails to build with GCC 10

### ISSUE THREAD

**Issue by MarcosFouces** [nmap/ncrack#77]
Hello
I forward you a bug this bug from Debian:
The package fails to build in a test rebuild on at least amd64 with gcc-10/g++-10, but succeeds to build with gcc-9/g++-9. 
The full build log can be found at:
http://people.debian.org/~doko/logs/gcc10-20200225/ncrack_0.7+debian-1_unstable_gcc10.log

**Comment by ithilgore** [comment]
Fixed by https://github.com/nmap/ncrack/pull/83
