### ISSUE TITLE
Meet problem when make on CentOS 7.6

### ISSUE THREAD

**Issue by HarveyXJ** [nmap/ncrack#88]
CentOS Linux release 7.6.1810
ncrack 0.8 
When did the make, met following problem:
g++ -Lnbase -Lnsock/src -Lopensshlib   -o ncrack ncrack.o utils.o TargetGroup.o Target.o targets.o NcrackOps.o Service.o ServiceGroup.o Connection.o services.o timing.o ncrack_error.o output.o ncrack_tty.o Buf.o NcrackOutputTable.o ncrack_input.o ncrack_resume.o crypto.o http.o http_digest.o xml.o ntlmssp.o modules/ncrack_ssh.o modules/ncrack_smb.o modules/ncrack_smb2.o modules/ncrack_rdp.o modules/ncrack_sip.o modules/ncrack_psql.o modules/ncrack_mysql.o modules/ncrack_winrm.o modules/ncrack_mongodb.o modules/ncrack_ftp.o modules/ncrack_telnet.o modules/ncrack_http.o modules/ncrack_pop3.o modules/ncrack_vnc.o modules/ncrack_redis.o modules/ncrack_owa.o modules/ncrack_imap.o modules/ncrack_cassandra.o modules/ncrack_mssql.o modules/ncrack_cvs.o modules/ncrack_wordpress.o modules/ncrack_webform.o modules/ncrack_joomla.o modules/ncrack_dicom.o modules/ncrack_mqtt.o -lnsock -lnbase -lssl -lcrypto -lopenssh
opensshlib/libopenssh.a(kexdhc.o)：在函数‘kexdh_client’中：
/opt/ncrack-0.8/opensshlib/kexdhc.c:80：对‘DH_get0_key’未定义的引用
opensshlib/libopenssh.a(kexdhc.o)：在函数‘ncrackssh_input_kex_dh’中：
/opt/ncrack-0.8/opensshlib/kexdhc.c:169：对‘DH_get0_key’未定义的引用
opensshlib/libopenssh.a(kexgexc.o)：在函数‘ncrackssh_input_kex_dh_gex_group’中：
/opt/ncrack-0.8/opensshlib/kexgexc.c:129：对‘DH_get0_key’未定义的引用
opensshlib/libopenssh.a(kexgexc.o)：在函数‘ncrackssh_input_kex_dh_gex_reply’中：
/opt/ncrack-0.8/opensshlib/kexgexc.c:232：对‘DH_get0_key’未定义的引用
/opt/ncrack-0.8/opensshlib/kexgexc.c:233：对‘DH_get0_pqg’未定义的引用
opensshlib/libopenssh.a(digest-openssl.o)：在函数‘ssh_digest_free’中：
/opt/ncrack-0.8/opensshlib/digest-openssl.c:179：对‘EVP_MD_CTX_free’未定义的引用
opensshlib/libopenssh.a(digest-openssl.o)：在函数‘ssh_digest_start’中：
/opt/ncrack-0.8/opensshlib/digest-openssl.c:121：对‘EVP_MD_CTX_new’未定义的引用
opensshlib/libopenssh.a(sshkey.o)：在函数‘to_blob_buf’中：
/opt/ncrack-0.8/opensshlib/sshkey.c:791：对‘DSA_get0_pqg’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:792：对‘DSA_get0_key’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:816：对‘RSA_get0_key’未定义的引用
opensshlib/libopenssh.a(sshkey.o)：在函数‘sshkey_size’中：
/opt/ncrack-0.8/opensshlib/sshkey.c:290：对‘DSA_get0_key’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:286：对‘RSA_get0_key’未定义的引用
opensshlib/libopenssh.a(sshkey.o)：在函数‘sshkey_add_private’中：
/opt/ncrack-0.8/opensshlib/sshkey.c:561：对‘RSA_set0_key’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:562：对‘RSA_set0_factors’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:563：对‘RSA_set0_crt_params’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:568：对‘DSA_set0_key’未定义的引用
opensshlib/libopenssh.a(sshkey.o)：在函数‘sshkey_new’中：
/opt/ncrack-0.8/opensshlib/sshkey.c:502：对‘RSA_set0_key’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:517：对‘DSA_set0_pqg’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:518：对‘DSA_set0_key’未定义的引用
opensshlib/libopenssh.a(sshkey.o)：在函数‘sshkey_equal_public’中：
/opt/ncrack-0.8/opensshlib/sshkey.c:703：对‘DSA_get0_pqg’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:704：对‘DSA_get0_pqg’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:705：对‘DSA_get0_key’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:706：对‘DSA_get0_key’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:696：对‘RSA_get0_key’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:697：对‘RSA_get0_key’未定义的引用
opensshlib/libopenssh.a(sshkey.o)：在函数‘sshkey_fingerprint_raw’中：
/opt/ncrack-0.8/opensshlib/sshkey.c:929：对‘RSA_get0_key’未定义的引用
opensshlib/libopenssh.a(sshkey.o)：在函数‘sshkey_from_private’中：
/opt/ncrack-0.8/opensshlib/sshkey.c:1826：对‘DSA_get0_pqg’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:1827：对‘DSA_get0_key’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:1828：对‘DSA_set0_pqg’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:1829：对‘DSA_set0_key’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:1857：对‘RSA_get0_key’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:1858：对‘RSA_set0_key’未定义的引用
opensshlib/libopenssh.a(sshkey.o)：在函数‘sshkey_demote’中：
/opt/ncrack-0.8/opensshlib/sshkey.c:2339：对‘RSA_get0_key’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:2341：对‘RSA_set0_key’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:2351：对‘DSA_get0_pqg’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:2352：对‘DSA_get0_key’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:2354：对‘DSA_set0_pqg’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:2355：对‘DSA_set0_key’未定义的引用
opensshlib/libopenssh.a(sshkey.o)：在函数‘sshkey_certify’中：
/opt/ncrack-0.8/opensshlib/sshkey.c:2501：对‘RSA_get0_key’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:2482：对‘DSA_get0_pqg’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:2483：对‘DSA_get0_key’未定义的引用
opensshlib/libopenssh.a(sshkey.o)：在函数‘sshkey_private_serialize’中：
/opt/ncrack-0.8/opensshlib/sshkey.c:2632：对‘RSA_get0_key’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:2633：对‘RSA_get0_factors’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:2634：对‘RSA_get0_crt_params’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:2659：对‘DSA_get0_pqg’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:2660：对‘DSA_get0_key’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:2669：对‘DSA_get0_key’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:2648：对‘RSA_get0_key’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:2649：对‘RSA_get0_factors’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:2650：对‘RSA_get0_crt_params’未定义的引用
opensshlib/libopenssh.a(sshkey.o)：在函数‘sshkey_from_blob_internal’中：
/opt/ncrack-0.8/opensshlib/sshkey.c:2065：对‘RSA_set0_key’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:2085：对‘DSA_get0_pqg’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:2086：对‘DSA_get0_key’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:2091：对‘DSA_set0_pqg’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:2092：对‘DSA_set0_key’未定义的引用
opensshlib/libopenssh.a(sshkey.o)：在函数‘sshkey_private_deserialize’中：
/opt/ncrack-0.8/opensshlib/sshkey.c:2846：对‘RSA_set0_key’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:2773：对‘DSA_set0_key’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:2764：对‘DSA_set0_pqg’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:2765：对‘DSA_set0_key’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:2863：对‘RSA_set0_key’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:2864：对‘RSA_set0_factors’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:2865：对‘RSA_set0_crt_params’未定义的引用
/opt/ncrack-0.8/opensshlib/sshkey.c:2847：对‘RSA_set0_factors’未定义的引用
opensshlib/libopenssh.a(ssh-ecdsa.o)：在函数‘ssh_ecdsa_sign’中：
/opt/ncrack-0.8/opensshlib/ssh-ecdsa.c:84：对‘ECDSA_SIG_get0’未定义的引用
opensshlib/libopenssh.a(ssh-ecdsa.o)：在函数‘ssh_ecdsa_verify’中：
/opt/ncrack-0.8/opensshlib/ssh-ecdsa.c:163：对‘ECDSA_SIG_set0’未定义的引用
opensshlib/libopenssh.a(cipher.o)：在函数‘cipher_get_keyiv’中：
/opt/ncrack-0.8/opensshlib/cipher.c:571：对‘EVP_CIPHER_CTX_iv’未定义的引用
opensshlib/libopenssh.a(cipher.o)：在函数‘cipher_set_keyiv’中：
/opt/ncrack-0.8/opensshlib/cipher.c:614：对‘EVP_CIPHER_CTX_iv_noconst’未定义的引用
opensshlib/libopenssh.a(cipher.o)：在函数‘cipher_get_keycontext’中：
/opt/ncrack-0.8/opensshlib/cipher.c:641：对‘EVP_CIPHER_impl_ctx_size’未定义的引用
/opt/ncrack-0.8/opensshlib/cipher.c:644：对‘EVP_CIPHER_CTX_get_cipher_data’未定义的引用
opensshlib/libopenssh.a(cipher.o)：在函数‘cipher_set_keycontext’中：
/opt/ncrack-0.8/opensshlib/cipher.c:660：对‘EVP_CIPHER_impl_ctx_size’未定义的引用
/opt/ncrack-0.8/opensshlib/cipher.c:661：对‘EVP_CIPHER_CTX_get_cipher_data’未定义的引用
opensshlib/libopenssh.a(rsa.o)：在函数‘rsa_public_encrypt’中：
/opt/ncrack-0.8/opensshlib/rsa.c:81：对‘RSA_get0_key’未定义的引用
opensshlib/libopenssh.a(rsa.o)：在函数‘rsa_private_decrypt’中：
/opt/ncrack-0.8/opensshlib/rsa.c:130：对‘RSA_get0_key’未定义的引用
opensshlib/libopenssh.a(rsa.o)：在函数‘rsa_generate_additional_parameters’中：
/opt/ncrack-0.8/opensshlib/rsa.c:176：对‘RSA_get0_key’未定义的引用
/opt/ncrack-0.8/opensshlib/rsa.c:177：对‘RSA_get0_factors’未定义的引用
/opt/ncrack-0.8/opensshlib/rsa.c:178：对‘RSA_get0_crt_params’未定义的引用
opensshlib/libopenssh.a(ssh-dss.o)：在函数‘ssh_dss_sign’中：
/opt/ncrack-0.8/opensshlib/ssh-dss.c:81：对‘DSA_SIG_get0’未定义的引用
opensshlib/libopenssh.a(ssh-dss.o)：在函数‘ssh_dss_verify’中：
/opt/ncrack-0.8/opensshlib/ssh-dss.c:188：对‘DSA_SIG_get0’未定义的引用
opensshlib/libopenssh.a(ssh-rsa.o)：在函数‘ssh_rsa_verify’中：
/opt/ncrack-0.8/opensshlib/ssh-rsa.c:135：对‘RSA_get0_key’未定义的引用
opensshlib/libopenssh.a(dh.o)：在函数‘dh_pub_is_valid’中：
/opt/ncrack-0.8/opensshlib/dh.c:240：对‘DH_get0_pqg’未定义的引用
opensshlib/libopenssh.a(dh.o)：在函数‘dh_gen_key’中：
/opt/ncrack-0.8/opensshlib/dh.c:267：对‘DH_get0_pqg’未定义的引用
/opt/ncrack-0.8/opensshlib/dh.c:273：对‘DH_set_length’未定义的引用
/opt/ncrack-0.8/opensshlib/dh.c:275：对‘DH_get0_key’未定义的引用
opensshlib/libopenssh.a(dh.o)：在函数‘dh_new_group_asc’中：
/opt/ncrack-0.8/opensshlib/dh.c:291：对‘DH_get0_pqg’未定义的引用
opensshlib/libopenssh.a(dh.o)：在函数‘dh_new_group’中：
/opt/ncrack-0.8/opensshlib/dh.c:312：对‘DH_set0_pqg’未定义的引用
collect2: 错误：ld 返回 1
make[1]: *** [ncrack] 错误 1
make[1]: 离开目录“/opt/ncrack-0.8”
make: *** [all] 错误 2

**Comment by DengLZ** [comment]
I ran into the same problem!
Is your problem solved?

**Comment by HarveyXJ** [comment]
> I ran into the same problem!
> Is your problem solved?

It's not solved yet.

**Comment by ithilgore** [comment]
Do you have openssl development libraries installed in your system? 

yum install openssl-devel

**Comment by HarveyXJ** [comment]
> Do you have openssl development libraries installed in your system?
> 
> yum install openssl-devel
yes 
I have already  install openssl-devel-1.0.2k-19.e17.x86_64
but don't solved it

**Comment by DengLZ** [comment]
Already installed,  it's not work.

`Compiling Ncrack...
rm -f ncrack
g++ -Lnbase -Lnsock/src -Lopensshlib   -o ncrack ncrack.o utils.o TargetGroup.o Target.o targets.o NcrackOps.o Service.o ServiceGroup.o Connection.o services.o timing.o ncrack_error.o output.o ncrack_tty.o Buf.o NcrackOutputTable.o ncrack_input.o ncrack_resume.o crypto.o http.o http_digest.o xml.o ntlmssp.o modules/ncrack_ssh.o modules/ncrack_smb.o modules/ncrack_smb2.o modules/ncrack_rdp.o modules/ncrack_sip.o modules/ncrack_psql.o modules/ncrack_mysql.o modules/ncrack_winrm.o modules/ncrack_mongodb.o modules/ncrack_ftp.o modules/ncrack_telnet.o modules/ncrack_http.o modules/ncrack_pop3.o modules/ncrack_vnc.o modules/ncrack_redis.o modules/ncrack_owa.o modules/ncrack_imap.o modules/ncrack_cassandra.o modules/ncrack_mssql.o modules/ncrack_cvs.o modules/ncrack_wordpress.o modules/ncrack_joomla.o modules/ncrack_dicom.o modules/ncrack_mqtt.o -lnsock -lnbase -lssl -lcrypto -lopenssh 
opensshlib/libopenssh.a(kexdhc.o): In function `kexdh_client':
/root/ncrack-0.7/opensshlib/kexdhc.c:80: undefined reference to `DH_get0_key'
opensshlib/libopenssh.a(kexdhc.o): In function `ncrackssh_input_kex_dh':
/root/ncrack-0.7/opensshlib/kexdhc.c:169: undefined reference to `DH_get0_key'
opensshlib/libopenssh.a(kexgexc.o): In function `ncrackssh_input_kex_dh_gex_group':
/root/ncrack-0.7/opensshlib/kexgexc.c:129: undefined reference to `DH_get0_key'
opensshlib/libopenssh.a(kexgexc.o): In function `ncrackssh_input_kex_dh_gex_reply':
/root/ncrack-0.7/opensshlib/kexgexc.c:232: undefined reference to `DH_get0_key'
/root/ncrack-0.7/opensshlib/kexgexc.c:233: undefined reference to `DH_get0_pqg'
opensshlib/libopenssh.a(digest-openssl.o): In function `ssh_digest_free':
/root/ncrack-0.7/opensshlib/digest-openssl.c:179: undefined reference to `EVP_MD_CTX_free'
opensshlib/libopenssh.a(digest-openssl.o): In function `ssh_digest_start':
/root/ncrack-0.7/opensshlib/digest-openssl.c:121: undefined reference to `EVP_MD_CTX_new'
opensshlib/libopenssh.a(sshkey.o): In function `to_blob_buf':
/root/ncrack-0.7/opensshlib/s

# rpm -qa | grep openssl-devel
openssl-devel-1.0.2k-19.el7.x86_64
`

**Comment by HarveyXJ** [comment]
> Already installed, it's not work.
> 
> `Compiling Ncrack... rm -f ncrack g++ -Lnbase -Lnsock/src -Lopensshlib -o ncrack ncrack.o utils.o TargetGroup.o Target.o targets.o NcrackOps.o Service.o ServiceGroup.o Connection.o services.o timing.o ncrack_error.o output.o ncrack_tty.o Buf.o NcrackOutputTable.o ncrack_input.o ncrack_resume.o crypto.o http.o http_digest.o xml.o ntlmssp.o modules/ncrack_ssh.o modules/ncrack_smb.o modules/ncrack_smb2.o modules/ncrack_rdp.o modules/ncrack_sip.o modules/ncrack_psql.o modules/ncrack_mysql.o modules/ncrack_winrm.o modules/ncrack_mongodb.o modules/ncrack_ftp.o modules/ncrack_telnet.o modules/ncrack_http.o modules/ncrack_pop3.o modules/ncrack_vnc.o modules/ncrack_redis.o modules/ncrack_owa.o modules/ncrack_imap.o modules/ncrack_cassandra.o modules/ncrack_mssql.o modules/ncrack_cvs.o modules/ncrack_wordpress.o modules/ncrack_joomla.o modules/ncrack_dicom.o modules/ncrack_mqtt.o -lnsock -lnbase -lssl -lcrypto -lopenssh opensshlib/libopenssh.a(kexdhc.o): In function `kexdh_client':
> /root/ncrack-0.7/opensshlib/kexdhc.c:80: undefined reference to `DH_get0_key' opensshlib/libopenssh.a(kexdhc.o): In function `ncrackssh_input_kex_dh':
> /root/ncrack-0.7/opensshlib/kexdhc.c:169: undefined reference to `DH_get0_key' opensshlib/libopenssh.a(kexgexc.o): In function `ncrackssh_input_kex_dh_gex_group':
> /root/ncrack-0.7/opensshlib/kexgexc.c:129: undefined reference to `DH_get0_key' opensshlib/libopenssh.a(kexgexc.o): In function `ncrackssh_input_kex_dh_gex_reply':
> /root/ncrack-0.7/opensshlib/kexgexc.c:232: undefined reference to `DH_get0_key' /root/ncrack-0.7/opensshlib/kexgexc.c:233: undefined reference to `DH_get0_pqg'
> opensshlib/libopenssh.a(digest-openssl.o): In function `ssh_digest_free': /root/ncrack-0.7/opensshlib/digest-openssl.c:179: undefined reference to `EVP_MD_CTX_free'
> opensshlib/libopenssh.a(digest-openssl.o): In function `ssh_digest_start': /root/ncrack-0.7/opensshlib/digest-openssl.c:121: undefined reference to `EVP_MD_CTX_new'
> opensshlib/libopenssh.a(sshkey.o): In function `to_blob_buf':
> /root/ncrack-0.7/opensshlib/s
> 
> # rpm -qa | grep openssl-devel
> openssl-devel-1.0.2k-19.el7.x86_64
> `

Maybe you can try ncrack-0.8

**Comment by ithilgore** [comment]
The problem is the openssl version in your system being < 1.1 . We do not currently support 1.0* 
You'll have to install openssl 1.1 or use an older Ncrack release.
